jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          echo "Runner is working"
          hostname
          whoami

